import type { Config } from "tailwindcss";

export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        terracotta: {
          50: "var(--tc-50)",
          100: "var(--tc-100)",
          200: "var(--tc-200)",
          300: "var(--tc-300)",
          400: "var(--tc-400)",
          500: "var(--tc-500)",
          600: "var(--tc-600)",
          700: "var(--tc-700)",
          800: "var(--tc-800)",
          900: "var(--tc-900)",
        },
        "teal-pine": {
          50: "var(--tp-50)",
          100: "var(--tp-100)",
          200: "var(--tp-200)",
          300: "var(--tp-300)",
          400: "var(--tp-400)",
          500: "var(--tp-500)",
          600: "var(--tp-600)",
          700: "var(--tp-700)",
          800: "var(--tp-800)",
          900: "var(--tp-900)",
        },
        butter: {
          50: "var(--bt-50)",
          100: "var(--bt-100)",
          200: "var(--bt-200)",
          300: "var(--bt-300)",
          400: "var(--bt-400)",
          500: "var(--bt-500)",
          600: "var(--bt-600)",
          700: "var(--bt-700)",
          800: "var(--bt-800)",
        },
        surface: {
          DEFAULT: "var(--surface)",
          raised: "var(--surface-raised)",
          sunken: "var(--surface-sunken)",
          line: "var(--surface-line)",
        },
        ink: {
          DEFAULT: "var(--ink)",
          soft: "var(--ink-soft)",
          mute: "var(--ink-mute)",
        },
        "terracotta-ink": "var(--terracotta-ink)",
        "teal-ink": "var(--teal-ink)",
        "teal-ink-deep": "var(--teal-ink-deep)",
        status: {
          new: "var(--status-new)",
          practicing: "var(--status-practicing)",
          nearly: "var(--status-nearly)",
          mastered: "var(--status-mastered)",
        },
        pd: {
          bg: "var(--pd-bg)",
          panel: "var(--pd-panel)",
          line: "var(--pd-line)",
          ink: "var(--pd-ink)",
          "ink-soft": "var(--pd-ink-soft)",
          accent: "var(--pd-accent)",
        },
      },
      fontFamily: {
        symbol: ["Andika", "sans-serif"],
        ui: ["Lexend", "sans-serif"],
      },
      fontSize: {
        xs: "var(--text-xs)",
        sm: "var(--text-sm)",
        base: "var(--text-base)",
        lg: "var(--text-lg)",
        xl: "var(--text-xl)",
        "2xl": "var(--text-2xl)",
        "3xl": "var(--text-3xl)",
        "symbol-map": "var(--symbol-map)",
        "symbol-choice": "var(--symbol-choice)",
        "symbol-hero": "var(--symbol-hero)",
      },
      spacing: {
        "safe-area": "var(--safe-area)",
      },
      borderRadius: {
        block: "var(--radius-block)",
        card: "var(--radius-card)",
        pill: "var(--radius-pill)",
        pd: "var(--radius-pd)",
      },
      transitionTimingFunction: {
        snap: "var(--ease-snap)",
        crisp: "var(--ease-crisp)",
      },
      transitionDuration: {
        fast: "var(--dur-fast)",
        normal: "var(--dur-normal)",
      },
    },
  },
  plugins: [],
} satisfies Config;
